from django.urls import path

from . import views

urlpatterns = [
    path("", views.video_list, name="video_list"),
    path("creator/analytics/", views.creator_analytics, name="creator_analytics"),
    path("creator/comments/", views.creator_comment_list, name="creator_comment_list"),
    path("creator/comments/moderate/", views.creator_comment_bulk_moderation, name="creator_comment_bulk_moderation"),
    path("creator/videos/", views.creator_video_list, name="creator_video_list"),
    path("creator/videos/publication/", views.creator_video_bulk_publication, name="creator_video_bulk_publication"),
    path("creator/videos/trash/", views.creator_video_trash, name="creator_video_trash"),
    path("notifications/", views.notification_list, name="notification_list"),
    path("notifications/read-all/", views.notification_mark_all_read, name="notification_mark_all_read"),
    path("notifications/<int:pk>/read/", views.notification_mark_read, name="notification_mark_read"),
    path("videos/<int:pk>/", views.video_detail, name="video_detail"),
    path("videos/shared/<uuid:token>/", views.shared_video_detail, name="shared_video_detail"),
    path("videos/<int:pk>/rotate-share-token/", views.video_rotate_share_token, name="video_rotate_share_token"),
    path("videos/<int:pk>/edit/", views.video_edit, name="video_edit"),
    path("videos/<int:pk>/delete/", views.video_delete, name="video_delete"),
    path("videos/<int:pk>/restore/", views.video_restore, name="video_restore"),
    path("videos/<int:pk>/permanent-delete/", views.video_permanent_delete, name="video_permanent_delete"),
    path("videos/<int:pk>/progress/", views.playback_progress, name="playback_progress"),
    path("videos/<int:pk>/comments/", views.add_comment, name="add_comment"),
    path("comments/<int:pk>/edit/", views.comment_edit, name="comment_edit"),
    path("comments/<int:pk>/delete/", views.comment_delete, name="comment_delete"),
    path("comments/<int:pk>/reply/", views.add_comment_reply, name="add_comment_reply"),
    path("videos/<int:pk>/like/", views.like_video, name="like_video"),
    path("videos/<int:pk>/dislike/", views.dislike_video, name="dislike_video"),
    path("channels/", views.channel_list, name="channel_list"),
    path("channels/<int:pk>/", views.channel_detail, name="channel_detail"),
    path("channels/<int:pk>/analytics/", views.channel_analytics, name="channel_analytics"),
    path("channels/<int:pk>/team/", views.channel_team, name="channel_team"),
    path("channels/<int:pk>/team/<int:membership_pk>/remove/", views.channel_team_remove, name="channel_team_remove"),
    path("channels/<int:pk>/subscribe/", views.subscribe, name="subscribe"),
    path("categories/", views.category_list, name="category_list"),
    path("categories/<int:pk>/", views.category_detail, name="category_detail"),
    path("search/", views.search, name="search"),
    path("filter/", views.filter_videos, name="filter"),
    path("profile/<str:username>/", views.user_profile, name="user_profile"),
    path("profile/<str:username>/edit/", views.edit_profile, name="edit_profile"),
    path("upload/", views.upload_video, name="upload"),
    path("playlists/", views.playlist_list, name="playlist_list"),
    path("playlists/create/", views.playlist_create, name="playlist_create"),
    path("playlists/<int:pk>/", views.playlist_detail, name="playlist_detail"),
    path("playlists/<int:pk>/edit/", views.playlist_edit, name="playlist_edit"),
    path("playlists/<int:pk>/delete/", views.playlist_delete, name="playlist_delete"),
    path("playlists/<int:pk>/videos/<int:video_pk>/add/", views.playlist_add_video, name="playlist_add_video"),
    path("playlists/<int:pk>/items/<int:item_pk>/remove/", views.playlist_remove_video, name="playlist_remove_video"),
    path("history/", views.watch_history, name="watch_history"),
    path("history/clear/", views.watch_history_clear, name="watch_history_clear"),
    path("history/<int:pk>/remove/", views.watch_history_remove, name="watch_history_remove"),
]
