# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video", "0002_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("visibility", models.CharField(choices=[("public", "Public"), ("unlisted", "Unlisted"), ("private", "Private")], default="private", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="playlists", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at", "name"]},
        ),
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("playlist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="video.playlist")),
                ("video", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="playlist_items", to="video.video")),
            ],
            options={"ordering": ["position", "added_at"]},
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(fields=("owner", "name"), name="unique_playlist_name_per_owner"),
        ),
        migrations.AddConstraint(
            model_name="playlistitem",
            constraint=models.UniqueConstraint(fields=("playlist", "video"), name="unique_video_per_playlist"),
        ),
    ]
