# Generated by Django 6.1 on 2026-08-21 03:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0019_channel_team_invitations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoWatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("playback_session_id", models.UUIDField()),
                ("viewer_session_hash", models.CharField(max_length=64)),
                ("watched_seconds", models.PositiveSmallIntegerField()),
                ("position_seconds", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_events",
                        to="video.video",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_watch_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["video", "created_at"], name="watch_video_created_idx"
                    ),
                    models.Index(
                        fields=["video", "playback_session_id"],
                        name="watch_video_session_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("watched_seconds__gte", 1), ("watched_seconds__lte", 15)
                        ),
                        name="watch_event_delta_between_1_and_15",
                    )
                ],
            },
        ),
    ]
