# Generated by Django 6.1 on 2026-08-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0020_video_watch_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("like", "Like"),
                    ("dislike", "Dislike"),
                    ("subscription", "Subscription"),
                    ("upload", "New upload"),
                    ("team_invite", "Team invitation"),
                ],
                max_length=20,
            ),
        ),
    ]
