# Generated by Django 6.1 on 2026-08-22 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0021_team_invitation_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_seconds", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=120)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="video.video",
                    ),
                ),
            ],
            options={
                "ordering": ["start_seconds", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("video", "start_seconds"),
                        name="unique_chapter_timestamp_per_video",
                    )
                ],
            },
        ),
    ]
