# Generated by Django 6.1 on 2026-08-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video", "0022_video_chapters"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_seconds", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="video.video",
                    ),
                ),
            ],
            options={
                "ordering": ["position_seconds", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "video", "position_seconds"),
                        name="unique_video_bookmark_position_per_user",
                    )
                ],
            },
        ),
    ]
