# Generated by Django 6.1.1

from django.db import migrations, models


def seed_bookmark_sort_positions(apps, schema_editor):
    VideoBookmark = apps.get_model("video", "VideoBookmark")
    user_ids = (
        VideoBookmark.objects.order_by()
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in user_ids.iterator():
        bookmarks = list(
            VideoBookmark.objects.filter(user_id=user_id)
            .order_by("-updated_at", "-pk")
        )
        for position, bookmark in enumerate(bookmarks):
            bookmark.sort_position = position
        if bookmarks:
            VideoBookmark.objects.bulk_update(bookmarks, ["sort_position"])


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0038_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="videobookmark",
            name="sort_position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            seed_bookmark_sort_positions,
            migrations.RunPython.noop,
        ),
    ]
